apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.port }}
  selector:
    app: kafka
