# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Container port
  type: loadbalancer       
