apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080       # Port exposed by the LoadBalancer
      targetPort: 8080 # Port inside the container
  type: LoadBalancer   # Expose service as a LoadBalancer
