apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: {{ .Values.webapp.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
